#@TYPE: Machine
#@NAME: rno-g-rev-N
#@DESCRIPTION: RNO-G Controller Board RevN with AM62x, 1-4 GB RAM
#@ARTICLENUMBERS: revN

include conf/machine/include/phyam62xx.inc

MACHINEOVERRIDES =. ":rno-g-revn:"

MACHINE_FEATURES += "emmc 3g"

KERNEL_OVERLAYS = ""

KERNEL_DEVICETREE = " \
    ti/k3-am625-rno-g-revN.dtb \
    ${KERNEL_OVERLAYS} \
"

UBOOT_MACHINE = "phycore_am62x_a53_defconfig"
