require conf/distro/ampliphy.conf

DISTRO_VERSION:prepend = "EeVanescent-"
DISTRO = "eevanescent"
DISTRO_NAME = "EeVanescent Liνx"
VERSION_CODENAME="Shadow Zone"


DISTRO_FEATURES:remove = "wayland opengl usbgadget gpu"
DISTRO_FEATURES_BACKFILL_CONSIDERED += "x11"


VIRTUAL-RUNTIME_login_manager = "shadow"

VIRTUAL-RUNTIME_network_manager = "systemd-networkd"
VIRTUAL-RUNTIME_base-utils = "coreutils"


IMAGE_LINGUAS = "en-us"

DISTRO_FEATURE:append = " ldconfig usbhost"
PACKAGE_CLASSES = "package_rpm"

PREFERRED_PROVIDER_os-release = "eevanescent-version"
PACKAGE_CONFIG:systemd += "udev-hwdb"

INHERIT:remove = "create-spdx"
