#! /usr/bin/sh

source /etc/profile.d/10-ubx-env.sh

# make sure PPS is on (and will socket-activate gpsd), set to 50 us on both pulses
ubxtool -z CFG-TP-LEN_LOCK_TP1,50,7
ubxtool -z CFG-TP-LEN_LOCK_TP2,50,7
ubxtool -z CFG-TP-LEN_TP1,10000,7  # 10 ms when don't have a lock
ubxtool -z CFG-TP-LEN_TP2,10000,7

# set baud rate to 115200
gpsctl -s 115200 /dev/ttyGPS

#enable binary mode, etc.
ubxtool -d NMEA
ubxtool -e BINARY 
ubxtool -e RAWX 

